# Generated by Django 4.2.7 on 2023-12-08 15:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_address', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('long', models.FloatField(blank=True)),
                ('lat', models.FloatField(blank=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=100)),
                ('survey_date', models.DateField(blank=True)),
                ('respondent_age', models.IntegerField(blank=True)),
                ('respondent_name', models.CharField(blank=True, max_length=100)),
                ('respondent_tenure', models.IntegerField(blank=True)),
                ('respondent_education', models.CharField(blank=True, max_length=100)),
                ('respondent_residency_type', models.CharField(blank=True, max_length=100)),
                ('respondent_occupation', models.CharField(blank=True, max_length=100)),
                ('respondent_civil_status', models.CharField(blank=True, max_length=100)),
                ('respondent_ethnicity', models.CharField(blank=True, max_length=100)),
                ('respondent_religion', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StormExperienced',
            fields=[
                ('storm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storm_name', models.CharField(blank=True, max_length=100)),
                ('survey_encode_datetime', models.DateTimeField(blank=True)),
                ('encoder_email_ad', models.EmailField(blank=True, max_length=254)),
                ('storm_duration', models.FloatField(blank=True)),
                ('storm_originate', models.CharField(blank=True, max_length=100)),
                ('storm_warning', models.CharField(blank=True, max_length=100)),
                ('storm_did_evacuate', models.CharField(blank=True, max_length=100)),
                ('storm_evacuate_loc', models.CharField(blank=True, max_length=100)),
                ('storm_evacuate_floodtime', models.CharField(blank=True, max_length=100)),
                ('storm_transpo', models.CharField(blank=True, max_length=100)),
                ('storm_disease', models.CharField(blank=True, max_length=100)),
                ('storm_loss', models.CharField(blank=True, max_length=100)),
                ('storm_work_school', models.CharField(blank=True, max_length=100)),
                ('storm_days_no_ws', models.IntegerField(blank=True)),
                ('storm_walkability', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('survey_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.survey')),
            ],
        ),
    ]
