# Generated by Django 4.2.7 on 2023-12-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_survey_district_alter_survey_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='respondent_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
